apiVersion: v1
kind: Service
metadata:
  name: kafka-messaging-service
  labels:
    app: kafka-service
    product: ness
spec:
  selector:
    app: kafka
    product: ness
  ports:
    - name: tcp-plaintext
      protocol: TCP
      port: 9092
      targetPort: 9092
    - name: tcp-controller
      protocol: TCP
      port: 9093
      targetPort: 9093