apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: jobqueues.navitaire.com
spec:
  group: navitaire.com
  scope: Namespaced
  names:
    plural: jobqueues
    singular: jobqueue
    kind: JobQueue
    shortNames:
    - jq
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            apiVersion:
              description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources"
              type: string
            kind:
              description: "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds"
              type: string
            spec:
              type: object
              description: "Spec defines the behavior of a job queue."
              properties:
                selector:
                  type: object
                  description: "Jobs with label keys and values matching this selector will be included in this job queue."
                  additionalProperties:
                    type: string
              required:
              - selector
            status:
              type: object
              description: "Most recently observed status of the job queue. Populated by the system. Read-only. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#spec-and-status"
              properties:
                queue:
                  type: array
                  description: "Current status of the queue."
                  items:
                    type: string
                activeJob:
                  type: string
                  description: "The name of the currently running job."
          required:
          - spec
      subresources:
        status: {}

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: jobqueue-status-updater
rules:
  - apiGroups:
      - navitaire.com # Replace with your CRD's group
    resources:
      - jobqueues/status # Replace 'jobqueues' with the plural name of your resource
    verbs:
      - patch

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jobqueue-status-updater-binding
subjects:
  - kind: ServiceAccount # Can also be User or Group
    name: default # Replace with the name of the service account
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: jobqueue-status-updater # Name of the Role to bin