apiVersion: navitaire.com/v1
kind: EventJob
metadata:
  name: eventjob
spec:
  eventName: "monitors.file.added"
  jobTemplate:
    metadata:
      labels:
        jobs/queue-enabled: "true"
    spec:
      template:
        spec:
          containers:
          - name: busybox
            image: busybox
            command: ["/bin/sh"]
            args: ["-c", "sleep 10;"]
          restartPolicy: Never