apiVersion: batch/v1
kind: Job
metadata:
  name: busybox-job
spec:
  suspend: true
  template:
    spec:
      containers:
      - name: busybox
        image: busybox
        command: ["sleep", "10"]
      restartPolicy: Never
  backoffLimit: 4