apiVersion: batch/v1
kind: Job
metadata:
  name: yes-label-1
  labels:
    jobs/queue-enabled: "true"
spec:
  template:
    spec:
      containers:
      - name: busybox
        image: busybox
        command: ["sleep", "30"]
      restartPolicy: Never
  backoffLimit: 4