apiVersion: batch/v1
kind: Job
metadata:
  name: no-label-3
spec:
  template:
    spec:
      containers:
      - name: busybox
        image: busybox
        command: ["sleep", "30"]
      restartPolicy: Never
  backoffLimit: 4