apiVersion: batch/v1
kind: CronJob
metadata:
  name: cronjob
spec:
  schedule: "* * * * *"
  jobTemplate:
    metadata:
      labels:
        jobs/queue-enabled: "true"
    spec:
      template:
        spec:
          containers:
          - name: busybox
            image: busybox
            command: ["sleep", "30"]
          restartPolicy: Never