apiVersion: batch/v1
kind: Job
metadata:
  name: parallel-job
  labels:
    jobs/queue-enabled: "true"
spec:
  completions: 4
  parallelism: 2
  template:
    spec:
      containers:
      - name: busybox
        image: busybox
        command: ["sleep", "30"]
      restartPolicy: Never